/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package day7package;

/**
 *
 * @author katri
 */
public class GUI_ extends javax.swing.JPanel {

    String pirmSkaitlis; //skaitlis2;
    String zime= "";
    boolean darbiba = false;
    
    
    /**
     * Creates new form GUI_
     */
    public GUI_() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        Text = new javax.swing.JTextField();
        Minus = new javax.swing.JButton();
        Plus = new javax.swing.JButton();
        Equal1 = new javax.swing.JButton();
        Dalijums = new javax.swing.JButton();
        Reizinajums = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        Kapinasana = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 255));

        jButton1.setBackground(new java.awt.Color(255, 153, 153));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("1");
        jButton1.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 153));
        jButton3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton3.setText("3");
        jButton3.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 153, 153));
        jButton4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton4.setText("4");
        jButton4.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 153, 153));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("2");
        jButton2.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(255, 153, 153));
        jButton5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton5.setText("5");
        jButton5.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(255, 153, 153));
        jButton6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton6.setText("6");
        jButton6.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(255, 153, 153));
        jButton7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton7.setText("7");
        jButton7.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(new java.awt.Color(255, 153, 153));
        jButton8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton8.setText("8");
        jButton8.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 153, 153));
        jButton9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton9.setText("9");
        jButton9.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(255, 153, 153));
        jButton10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton10.setText("0");
        jButton10.setMargin(new java.awt.Insets(2, 18, 2, 18));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        Text.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Text.setMinimumSize(new java.awt.Dimension(9, 24));
        Text.setPreferredSize(new java.awt.Dimension(20, 23));

        Minus.setBackground(new java.awt.Color(51, 255, 51));
        Minus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Minus.setText("-");
        Minus.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Minus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MinusActionPerformed(evt);
            }
        });

        Plus.setBackground(new java.awt.Color(51, 255, 51));
        Plus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Plus.setText("+");
        Plus.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Plus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PlusActionPerformed(evt);
            }
        });

        Equal1.setBackground(new java.awt.Color(51, 255, 51));
        Equal1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Equal1.setText("=");
        Equal1.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Equal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Equal1ActionPerformed(evt);
            }
        });

        Dalijums.setBackground(new java.awt.Color(51, 255, 51));
        Dalijums.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Dalijums.setText("/");
        Dalijums.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Dalijums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DalijumsActionPerformed(evt);
            }
        });

        Reizinajums.setBackground(new java.awt.Color(51, 255, 51));
        Reizinajums.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Reizinajums.setText("*");
        Reizinajums.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Reizinajums.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReizinajumsActionPerformed(evt);
            }
        });

        Clear.setBackground(new java.awt.Color(51, 255, 51));
        Clear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Clear.setText("CE");
        Clear.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });

        Kapinasana.setBackground(new java.awt.Color(51, 255, 51));
        Kapinasana.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        Kapinasana.setText("Xx");
        Kapinasana.setMargin(new java.awt.Insets(2, 18, 2, 18));
        Kapinasana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KapinasanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton7)
                            .addComponent(jButton4)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addGap(18, 18, 18)
                                .addComponent(jButton6))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton8)
                                .addGap(18, 18, 18)
                                .addComponent(jButton9)))
                        .addGap(50, 50, 50)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Plus)
                                    .addComponent(Equal1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Reizinajums)
                                        .addGap(31, 31, 31)
                                        .addComponent(Kapinasana))
                                    .addComponent(Dalijums)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Minus)
                                .addGap(18, 18, 18)
                                .addComponent(Clear)))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Text, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(Minus)
                    .addComponent(Clear))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(Plus)
                    .addComponent(Reizinajums)
                    .addComponent(Kapinasana))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jButton8)
                    .addComponent(jButton9)
                    .addComponent(Equal1)
                    .addComponent(Dalijums))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton10)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      SkaitluParadisana("1");
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SkaitluParadisana("2");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        SkaitluParadisana("3");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        SkaitluParadisana("4");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        SkaitluParadisana("5");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        SkaitluParadisana("6");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        SkaitluParadisana("7");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        SkaitluParadisana("8");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        SkaitluParadisana("9");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        SkaitluParadisana("0");
    }//GEN-LAST:event_jButton10ActionPerformed
private void SkaitluParadisana(String poga){
              
       String currenctText = Text.getText();
       
       if (currenctText.equals("0") ||currenctText.equals("*") || currenctText.equals("+")||currenctText.equals("-")
               ||currenctText.equals("/")){
           currenctText = "";
       }
        Text.setText(currenctText + poga);
    }
    private void PlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PlusActionPerformed
        pirmSkaitlis = Text.getText();
        
        darbiba = true;
        zime = "+";
        Text.setText("0");
        
    }//GEN-LAST:event_PlusActionPerformed

    private void Equal1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Equal1ActionPerformed
        if (darbiba){
            int skaitlis1 = Integer.valueOf(pirmSkaitlis);
            int skaitlis2 = Integer.valueOf(Text.getText());
            Aprekini rekins = new Aprekini();
            
            Text.setText(rekins.Aprekinat(skaitlis1, skaitlis2, zime));
            darbiba = false;
            zime = "";
        }
        
    }//GEN-LAST:event_Equal1ActionPerformed

    private void MinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MinusActionPerformed
        pirmSkaitlis = Text.getText();
        darbiba = true;
        zime = "-";
        Text.setText("0");
    }//GEN-LAST:event_MinusActionPerformed

    private void DalijumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DalijumsActionPerformed
        pirmSkaitlis = Text.getText();
        darbiba = true;
        zime = "/";
        Text.setText("0");
    }//GEN-LAST:event_DalijumsActionPerformed

    private void ReizinajumsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReizinajumsActionPerformed
        pirmSkaitlis = Text.getText();
        darbiba = true;
        zime = "*";
        Text.setText("0");
    }//GEN-LAST:event_ReizinajumsActionPerformed

    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        // TODO add your handling code here:
        Text.setText("0");
    }//GEN-LAST:event_ClearActionPerformed

    private void KapinasanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KapinasanaActionPerformed
        // TODO add your handling code here:
        pirmSkaitlis = Text.getText();
        darbiba = true;
        zime = "x";
        Text.setText("0");
    }//GEN-LAST:event_KapinasanaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton Dalijums;
    private javax.swing.JButton Equal1;
    private javax.swing.JButton Kapinasana;
    private javax.swing.JButton Minus;
    private javax.swing.JButton Plus;
    private javax.swing.JButton Reizinajums;
    private javax.swing.JTextField Text;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
